# Generated by Django 3.1.7 on 2021-03-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(default=None, max_length=255)),
                ('eligibility', models.CharField(default=None, max_length=500)),
                ('resource_description', models.CharField(default=None, max_length=1000)),
                ('office_hours', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('website_link', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='resources.category')),
            ],
        ),
    ]
