# Generated by Django 3.1.7 on 2021-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(default=None, max_length=255)),
                ('longitude', models.CharField(default=None, max_length=500)),
                ('street', models.CharField(default=None, max_length=1000)),
                ('city', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
