# Generated by Django 3.1.7 on 2021-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210314_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
